Nigeria Electronics Sales Performance & Business Insights Dashboard

This dashboard represents the sales performance of electronic products across Nigeria, focusing on revenue, units sold, product performance, daily sales trends, yearly sales, customers, and sales channels.

It helps a business understand which products generate the most revenue, when sales are high, which customers contribute more, and how sales are distributed across different channels.

🔢 1. Total Unit Sold

7K Units

This KPI shows the total number of electronic products sold during the selected period.

👉 It gives a quick idea of the overall sales volume.

💰 2. Total Sales

903.10M

This represents the total revenue generated from all electronic products.

Your dashboard is showing approximately 903.1 million in total sales.

👉 This is the most important revenue KPI for measuring overall business performance.

📅 3. Sales by Day

This chart shows how total sales vary across different days of the month.

For example, you can identify:

High-performing sales days
Low-performing days
Sales fluctuations
Peak sales periods

👉 This can help the company understand which days generate the highest revenue.

🎧 4. Sales by Product

This is one of the most useful charts in your dashboard.

It compares revenue generated by each electronic product.

From your dashboard, approximately:

Product	Performance
⌨️ Keyboard	Highest
📱 Phone	Very High
🎧 Headphones	High
📱 Tablet	High
🖥️ Monitor	Medium
🔌 Charger	Medium
💻 Laptop	Low
📷 Camera	Lowest
Key insight:

Keyboard and Phone are the strongest revenue-generating products, while Camera and Laptop contribute relatively less revenue.

👉 A business can use this information for inventory planning, promotions, and product strategy.

📈 5. Sales by Year

Your dashboard compares sales across 2023, 2024, and 2025.

From the chart:

2023 → 17.64%
2024 → 51.16%
2025 → ~31.2%
Key insight:

2024 was the strongest sales year, contributing more than half of the total revenue.

This allows management to investigate what caused the strong performance in 2024.

👥 6. Customer Sales Table

The table shows:

Customer Name
Product purchased
Total Sales contributed by that customer

For example, your dashboard shows customers such as Alfred Galvan, Amber Kidd, Angela Lin, etc.

👉 This helps identify high-value customers and understand individual customer contributions to revenue.

🚚 7. Sales Channel

You have a slicer for:

Direct
Online
Retail
Unknown
Wholesale

This allows the user to filter the entire dashboard by sales channel.
